
image:
  repository: gcr.io/google-samples/hello-app
  pullPolicy: IfNotPresent
  tag: "1.0"

service:
  type: NodePort
  port: 8080

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30

resources: 
  requests:
    cpu: 1



